language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - if composer >/dev/null 2>&1; then composer self-update; else curl -s http://getcomposer.org/installer | php && php composer.phar install --dev; fi
    - composer update --no-dev